//! Cross-language parity: the Rust codec must reproduce the exact offset words generated by the
//! JS encoders (js/test-vectors.json). Regenerate vectors with `bun js/scripts/gen-test-vectors.js`.

use alloy_primitives::U256;
use multicall_scripter_codec::*;
use serde_json::Value;

const VECTORS: &str = include_str!("../../../../js/test-vectors.json");

fn u64s(v: &Value, key: &str) -> Vec<u64> {
    v[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap())
        .collect()
}

#[test]
fn matches_js_golden_vectors() {
    let vectors: Vec<Value> = serde_json::from_str(VECTORS).expect("parse test-vectors.json");
    assert!(!vectors.is_empty(), "no vectors loaded");

    for (i, v) in vectors.iter().enumerate() {
        let kind = v["kind"].as_str().unwrap();
        let expected: U256 = v["offset"].as_str().unwrap().parse().unwrap();

        let actual = match kind {
            "static_call" => {
                let mt: U256 = v["mem_target"].as_str().unwrap().parse().unwrap();
                let rl: U256 = v["result_length"].as_str().unwrap().parse().unwrap();
                static_call(mt, rl).unwrap()
            }
            "state_changing_call" => {
                state_changing_call(v["msg_value_index"].as_u64().unwrap()).unwrap()
            }
            "static_call_partial_return" => static_call_partial_return(
                &u64s(v, "mem_targets"),
                &u64s(v, "result_lengths"),
                &u64s(v, "return_offsets"),
                v["return_data_size"].as_u64().unwrap(),
            )
            .unwrap(),
            "call_partial_return" => call_partial_return(
                v["msg_value_index"].as_u64().unwrap(),
                &u64s(v, "mem_targets"),
                &u64s(v, "result_lengths"),
                &u64s(v, "return_offsets"),
                v["return_data_size"].as_u64().unwrap(),
            )
            .unwrap(),
            other => panic!("unknown vector kind: {other}"),
        };

        assert_eq!(actual, expected, "vector #{i} ({kind}) mismatch vs JS");
    }
}
