[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "prague"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
ffi = true

[profile.default.invariant]
fail_on_revert = true
