// Generates Rust constants from schema/offset-schema.json — the canonical source of truth shared
// by the Solidity, JavaScript, and Rust layers. Constants are NEVER hand-written here; edit the
// schema and rebuild. Output is written to $OUT_DIR/schema_constants.rs and included by lib.rs.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Deserialize)]
struct Schema {
    value_offset: u32,
    partial_return_vars: u32,
    flags: BTreeMap<String, Flag>,
}

#[derive(Deserialize)]
struct Flag {
    value: String,
}

fn main() {
    // codec manifest is at rust/crates/codec; the canonical schema lives at <repo>/schema/offset-schema.json
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let schema_path = manifest_dir
        .join("../../../schema/offset-schema.json")
        .canonicalize()
        .expect("cannot locate schema/offset-schema.json relative to codec crate");

    println!("cargo:rerun-if-changed={}", schema_path.display());

    let raw = fs::read_to_string(&schema_path).expect("failed to read offset-schema.json");
    let schema: Schema = serde_json::from_str(&raw).expect("failed to parse offset-schema.json");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from schema/offset-schema.json — do not edit.\n\n");
    out.push_str(&format!(
        "pub const VALUE_OFFSET: u32 = {};\n",
        schema.value_offset
    ));
    out.push_str(&format!(
        "pub const PARTIAL_RETURN_VARS: u32 = {};\n\n",
        schema.partial_return_vars
    ));

    // Per-flag u8 constants.
    for (name, flag) in &schema.flags {
        let value = parse_hex_u8(&flag.value);
        out.push_str(&format!("pub const {}: u8 = 0x{:02X};\n", name, value));
    }

    // Runtime table of (value, name) for validate_offset.
    out.push_str("\npub const FLAGS: &[(u8, &str)] = &[\n");
    for (name, flag) in &schema.flags {
        let value = parse_hex_u8(&flag.value);
        out.push_str(&format!("    (0x{:02X}, \"{}\"),\n", value, name));
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("schema_constants.rs");
    fs::write(&out_path, out).expect("failed to write schema_constants.rs");
}

fn parse_hex_u8(s: &str) -> u8 {
    let s = s.trim_start_matches("0x").trim_start_matches("0X");
    u8::from_str_radix(s, 16).unwrap_or_else(|_| panic!("invalid hex flag value: {s}"))
}
